version: '3'
services: 
    camap:
        build:
            context: .
            dockerfile: Dockerfile_camap
        depends_on:
            - db
        ports: 
            - "80:80"
    db:
        image: mariadb
