version: '3'
services: 
    camap:
        build:
            context: .
            dockerfile: Dockerfile_camap
        depends_on:
            - db
        ports: 
            - "80:80"
    db:
        image: mariadb
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: "apestogether"
            MYSQL_DATABASE: camap
            MYSQL_USER: camap
            MYSQL_PASSWORD: camaper